Update patch set 1
Patch Set 1:

This breaks compile on Mac. I need to debug further but here is the first error message:

frameworks/opt/emoji/EmojiFactory.cpp:1: error: switch -mcpu=cortex-a9 conflicts with -march= switch

Patch-set: 1